
tableTemplate = \
    '''BEGIN;
CREATE TABLE files(file_id INTEGER PRIMARY KEY, file_path TEXT UNIQUE NOT NULL, file_hash_name TEXT UNIQUE NOT NULL);
CREATE TABLE tag_groups(group_id INTEGER PRIMARY KEY, group_name TEXT UNIQUE NOT NULL);
CREATE TABLE tags(tag_id INTEGER PRIMARY KEY, tag_name TEXT NOT NULL, tag_group INTEGER NOT NULL, FOREIGN KEY(tag_group) REFERENCES tag_groups(group_id) ON DELETE RESTRICT ON UPDATE CASCADE, UNIQUE(tag_name, tag_group) ON CONFLICT FAIL);
CREATE TABLE tagged_files_m2m(tag INTEGER, file INTEGER, FOREIGN KEY(tag) REFERENCES tags(tag_id) ON DELETE RESTRICT ON UPDATE CASCADE, FOREIGN KEY(file) REFERENCES files(file_id) ON DELETE RESTRICT ON UPDATE CASCADE, UNIQUE(tag, file) ON CONFLICT FAIL);
COMMIT;
'''

